<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form"  method="POST">

	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="username">username : </label>
				<input id="username" type="text" name="username" data-required data-name="username" value="<?= htmlspecialchars($POST['username']) ?>">
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input id="password" type="password" name="password" data-required data-name="Mot de passe" value="<?= htmlspecialchars($POST['password']) ?>">
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Connexion">
		</li>
	</ul>
</form>